# Generated by Django 5.1.6 on 2026-05-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_sizes_alter_product_image_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
