# Generated by Django 5.1.6 on 2026-05-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
